BRMP-11053
GSA/cic pull request #225
Opened 2021-02-18 22:17 UTC by AubreyTharpe

https://cm-jira.usa.gov/browse/BRMP-11053

Changes
--
- CAF Read More field's text coming from drupal
- CAF Read More field now appears in the BPA Table
- BPA Table now has notices like the Acquisition Vehicle Table
- Notices now correctly display multiple notices
- BPA & AV scope fields now display as they're written in Drupal
- Ordering requirements in the BPA table no longer has hardcoded value -- `DRUPAL change was required`
- The date values now correctly display the date selected in drupal
- Ordering Activities now correctly display if they do not have a link
- Ordering Activities in the BPA table now use Drupal data

A drupal change is required to make the ordering requirements work properly. It was changed to a link with unlimited values.
![image](https://user-images.githubusercontent.com/30943861/108428647-e01b6d80-720c-11eb-8003-aa2a837b70e6.png)

2021-02-23 05:25 UTC, snoopysnake commented on src/components/features/acquisitions/acquisitionResources.js
> +                                        {av.cafReadMore ? (
av.cafReadMore && ...

2021-02-23 05:42 UTC, snoopysnake commented on src/components/features/acquisitions/acquisitionResources.js
> +                                        <div style={{whiteSpace: 'pre-line'}}>{av.scope}</div>
use USWDS class `.text-pre-wrap`

2021-02-23 05:47 UTC, snoopysnake commented on src/components/features/acquisitions/acquisitionResources.js
> +                                    <div>{bpa.contractAccessFee}</div>
bpa.contractAccessFee && ...

2021-02-23 05:49 UTC, snoopysnake requested changes
`pre-line` can be set with existing class

Should also add "No Acquisition Vehicles providers yet", etc. in bottom table

2021-02-23 15:26 UTC, AubreyTharpe commented
> Should also add "No Acquisition Vehicles providers yet", etc. in bottom table

Vague. Needs clarification.

2021-02-24 19:43 UTC, snoopysnake approved these changes
bueno

2021-02-24 19:55 UTC, merged